### ISSUE TITLE
Lodash out of date - High vulnerability

### ISSUE THREAD

**Issue by mnemanja** [jackwilsdon/craco-use-babelrc#2]
Hi @jackwilsdon,
Thank you for this library.

Can you please update the version of the `lodash` from `4.17.15` to =>`4.6.2`?
Thanks!
![Screenshot 2019-08-27 at 15 59 22](https://user-images.githubusercontent.com/1423218/63778480-2c6e4180-c8e5-11e9-89fc-a0ec3b1a6d60.png)

**Comment by jackwilsdon** [comment]
Hey @mnemanja. It looks like that dependency actually comes from [`@craco/craco`](https://github.com/sharegate/craco) - it might be worth opening an issue there.

**Comment by robguy21** [comment]
@jackwilsdon we'll need to upgrade to latest craco dependency to resolve this - I've created a PR here,  https://github.com/jackwilsdon/craco-use-babelrc/pull/7
